# Generated by Django 4.1.3 on 2022-12-11 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='gender',
        ),
    ]
